### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by anheru88** [leonardo15043/CRUD-Angular-Laravel#1]
Hola, estoy revisando el codigo y al momento de compilar me arroja un eror.

``Date: 2019-04-24T17:36:17.448Z
Hash: 78d2a9e14787178ebd02
Time: 4627ms
chunk {main} main.js, main.js.map (main) 1.88 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 93.1 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 147 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.13 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]

ERROR in src/app/components/login/login.component.ts(31,45): error TS2339: Property 'user' does not exist on type 'Object'.
src/app/components/login/login.component.ts(32,43): error TS2339: Property 'token' does not exist on type 'Object'.
``

Podrias por favor revisar, y corregir el error.

**Comment by leonardo15043** [comment]
Este error se soluciono en el commit [https://github.com/leonardo15043/CRUD-Angular-Laravel/commit/7b62a4d018fda751cea9b82d579fb6c736187e86](url)
